name: float
description: An app for managing your deadlines.

version: 1.0.4+6
publish_to: none
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^5.0.0-nullsafety.1
  rxdart: ^0.23.1
  google_sign_in: ^4.1.1
  firebase_messaging: ^10.0.1
  path_provider: ^2.0.0
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.19.3
  carousel_slider: ^3.0.0
  firebase_core: any
  firebase_auth: ^1.0.1
  fluttertoast: ^7.1.6
  shared_preferences: ^0.5.6+1
  cloud_firestore: ^1.0.1
  datetime_picker_formfield: ^2.0.0
  flutter_slidable: "^0.5.3"
  provider: ^4.0.2
  get_it: ^3.1.0
  get: ^4.1.4
  # bot_toast: ^2.2.1
  flutter_icons: ^1.0.0+1
  url_launcher: ^6.0.6
  share: ^0.6.1+1
  apple_sign_in: ^0.1.0
  # flutter_cupertino_date_picker: ^1.0.26+2

  google_fonts: ^2.0.0
  http: ^0.13.0
  image_picker: ^0.7.3
  firebase_storage: any
  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  back_pressed: ^0.0.2
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test: 
    sdk: flutter

#flutter packages pub run flutter_launcher_icons:main
# flutter_launcher_icons: ^0.9.0
flutter_icons:
  image_path: "assets/icon/logo.png"
  android: true
  ios: true

flutter:
  fonts:
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
    - family: Lato-BlackItalic
      fonts:
        - asset: assets/fonts/Lato-BlackItalic.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
  uses-material-design: true

  assets:
    - google_fonts/
    - assets/images/
    - assets/
    - assets/images/profile/
    - assets/images/float/
    - assets/images/signup/
    - assets/images/essaytennis/
    - assets/images/splash/
    - assets/resource/
    - assets/icon/
    - assets/profile/
